### ISSUE TITLE
To Inform some errors..

### ISSUE THREAD

**Issue by ted-jung** [JohnOmernik/dcosprep#2]
Hi, John

I'm now trying your script(DCSO) what you prepared for Ubuntu16.04.
while testing...found some issues..and now reporting it here.

[Working env]
Ubuntu 16.04 1-master,1-slave

[Issue]
There are two commands(mkdir, ln, rm) in a script not properly works.
The location of these commands is different by version of kernel.

<img width="767" alt="screen shot 2017-09-29 at 4 05 01 pm" src="https://user-images.githubusercontent.com/3975093/31004594-fb98cc9a-a52f-11e7-9a83-edfa5fd84c9e.png">

<img width="747" alt="screen shot 2017-09-29 at 4 04 16 pm" src="https://user-images.githubusercontent.com/3975093/31004578-ee150bb0-a52f-11e7-8395-a48ec3a2f292.png">

Those script is in originally at "dcos_install.sh"
It copied many *.service under /etc/systemd/system/*.service

Thanks for your help.

**Comment by JohnOmernik** [comment]
Hello Ted, I am sorry, I am not working with this repo any longer, I've moved all of my prep work to https://github.com/johnomernik/zetago

**Comment by ted-jung** [comment]
Ah ha~~
John, Thanks for your answer.

**Comment by ted-jung** [comment]
Ah ha~~
John, Thanks for your answer.

Closing this issue
